const state={session:null,cache:{customers:[],admins:[],servers:[],users:[],services:[],plans:[],logs:[]}};
const $=s=>document.querySelector(s); const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const errMap={username_min_3:'آیدی باید حداقل ۳ کاراکتر باشد.',password_min_8:'رمز باید حداقل ۸ کاراکتر باشد.',password_mismatch:'تکرار رمز یکسان نیست.',username_exists:'این آیدی قبلاً استفاده شده است.',last_admin:'حداقل یک ادمین باید باقی بماند.',invalid_customer:'اطلاعات کاربر پنل کامل یا معتبر نیست.',setup_completed:'اولین ادمین قبلاً ساخته شده است.',invalid_login:'آیدی یا رمز عبور اشتباه است.',setup_required:'ابتدا باید اولین ادمین ساخته شود.',account_not_found:'حساب کاربری پیدا نشد.',admin_only:'این بخش فقط برای ادمین است.',unauthorized:'نشست شما منقضی شده؛ دوباره وارد شوید.',setup_failed:'خطا در ساخت اولین ادمین. دوباره تلاش کنید.',account_update_failed:'خطا در بروزرسانی حساب. دوباره تلاش کنید.',too_many_attempts:'تعداد تلاش‌ها زیاد بود. چند دقیقه دیگر دوباره امتحان کنید.'};
function token(){return state.session?.token||''} function headers(){return {'Content-Type':'application/json',Authorization:'Bearer '+token()}}
async function api(path,opt={}){const base=(window.STRIX_API_BASE||'').replace(/\/$/,'');const r=await fetch(base+path,{...opt,headers:{...(opt.body!==undefined?{'Content-Type':'application/json'}:{}),...(opt.headers||{}),...(state.session?{Authorization:'Bearer '+token()}: {})}});let x={};try{x=await r.json()}catch{}if(r.status===401){logout();throw new Error('unauthorized')}if(!r.ok)throw new Error(errMap[x.error]||x.error||'خطا در ارتباط با Backend');return x}
function showError(id,msg){const e=$(id);if(e){e.textContent=msg;e.classList.toggle('hidden',!msg)}}
async function checkSetup(){['#setup','#login','#app'].forEach(x=>$(x)?.classList.add('hidden'));try{const x=await api('/api/setup/status');(x.needsSetup?$('#setup'):$('#login')).classList.remove('hidden')}catch(e){$('#login').classList.remove('hidden');showError('#loginError','Backend در دسترس نیست. سرور را اجرا کنید.')}}
async function createFirstAdmin(){showError('#setupError','');const username=$('#setupUser').value.trim(),p=$('#setupPass').value,p2=$('#setupPass2').value;if(p.length<8)return showError('#setupError','رمز ادمین باید حداقل ۸ کاراکتر باشد.');if(p!==p2)return showError('#setupError','تکرار رمز عبور با رمز اصلی یکسان نیست.');if(username.length<3)return showError('#setupError','آیدی ادمین باید حداقل ۳ کاراکتر باشد.');try{const x=await api('/api/setup/create-admin',{method:'POST',body:JSON.stringify({username,password:p,passwordConfirm:p2})});startSession(x);await enterApp()}catch(e){showError('#setupError',e.message)}}
async function login(){showError('#loginError','');const u=$('#loginUser').value.trim(),p=$('#loginPass').value;if(!u||!p)return showError('#loginError','آیدی و رمز عبور را وارد کنید.');try{const x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:u,password:p})});startSession(x);await enterApp()}catch(e){showError('#loginError',e.message)}}
function startSession(x){state.session={token:x.token,role:x.role,admin:x.admin||null,customer:x.customer||null};localStorage.setItem('strix_session',JSON.stringify(state.session))}
async function restore(){try{const s=JSON.parse(localStorage.getItem('strix_session')||'null');if(!s)return checkSetup();state.session=s;await api('/api/me');await enterApp()}catch{localStorage.removeItem('strix_session');state.session=null;checkSetup()}}
async function enterApp(){$('#setup').classList.add('hidden');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');buildNav();setIdentity();showPage('dashboard')}
function logout(){state.session=null;localStorage.removeItem('strix_session');$('#app').classList.add('hidden');checkSetup()}
function buildNav(){const admin=state.session.role==='admin';const items=admin?[['dashboard','⌂','داشبورد'],['customers','♟','کاربران پنل'],['admins','🛡','مدیران'],['servers','◈','سرورها'],['users','♙','کاربران'],['services','🔗','سرویس‌ها'],['plans','▣','پلن‌ها'],['logs','≡','گزارش‌ها'],['account','⚙','حساب کاربری']]:[['dashboard','⌂','داشبورد'],['users','♙','کاربران من'],['services','🔗','سرویس‌ها'],['plans','▣','پلن‌ها'],['account','⚙','حساب کاربری']];$('#nav').innerHTML=items.map(i=>`<button class="nav" data-page="${i[0]}" onclick="showPage('${i[0]}')"><b>${i[1]}</b><span>${i[2]}</span></button>`).join('')}
function setIdentity(){const a=state.session.role==='admin',u=a?state.session.admin.username:state.session.customer.username;$('#roleText').textContent=a?'مدیر اصلی':'کاربر پنل';$('#who').textContent=u;$('#whoSub').textContent=a?'Administrator':'Panel User';$('#avatar').textContent=u.slice(0,1).toUpperCase()}
const titles={dashboard:['داشبورد','مدیریت پنل'],customers:['کاربران پنل','ایجاد و مدیریت حساب‌های دارای دسترسی محدود'],admins:['مدیران','مدیریت مدیران سیستم'],servers:['سرورها','مدیریت سرورهای Marzban'],users:['کاربران','مدیریت کاربران و اشتراک‌ها'],services:['سرویس‌ها','مدیریت سرویس‌های اتصال'],plans:['پلن‌ها','مدیریت پلن‌ها'],logs:['گزارش‌ها','رویدادهای سیستم'],account:['حساب کاربری','تغییر آیدی و رمز عبور']};
async function showPage(id){$('#title').textContent=titles[id][0];$('#sub').textContent=titles[id][1];document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));const c=$('#content');c.innerHTML='<section class="page"><div class="loading">در حال بارگذاری…</div></section>';try{if(id==='dashboard')c.innerHTML=await dashboard();if(id==='customers')c.innerHTML=await customers();if(id==='admins')c.innerHTML=await admins();if(id==='servers')c.innerHTML=await servers();if(id==='users')c.innerHTML=await users();if(id==='services')c.innerHTML=await services();if(id==='plans')c.innerHTML=await plans();if(id==='logs')c.innerHTML=await logs();if(id==='account')c.innerHTML=account()}catch(e){c.innerHTML=`<section class="page"><div class="card empty">${esc(e.message)}</div></section>`}if(innerWidth<821)$('#sidebar').classList.remove('open')}
function table(heads,rows){return `<div class="table"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${heads.length}"><div class="empty">موردی وجود ندارد</div></td></tr>`}</tbody></table></div>`}
async function dashboard(){const u=await api('/api/users'),s=await api('/api/services'),p=await api('/api/plans');let extra=state.session.role==='admin'?await api('/api/customers'):null;return `<section class="page"><div class="hero"><div><div class="eyebrow">STRIX VIP PANEL</div><h2>داشبورد</h2><p>${state.session.role==='admin'?'مدیریت کامل پنل و حساب‌های مشتریان':'پنل اختصاصی شما با دسترسی محدود'}</p></div><button class="primary" onclick="showPage('account')">⚙ تنظیمات حساب</button></div><div class="stats"><div class="stat"><b>کاربران</b><strong>${u.length}</strong></div><div class="stat"><b>سرویس‌ها</b><strong>${s.length}</strong></div><div class="stat"><b>پلن‌ها</b><strong>${p.length}</strong></div><div class="stat"><b>${state.session.role==='admin'?'کاربران پنل':'وضعیت حساب'}</b><strong>${state.session.role==='admin'?extra.length:'فعال'}</strong></div></div><div class="grid2"><div class="card"><h3>دسترسی سریع</h3><div class="quick"><button onclick="showPage('users')">＋ کاربر جدید</button><button onclick="showPage('services')">＋ سرویس جدید</button><button onclick="showPage('plans')">＋ پلن جدید</button>${state.session.role==='admin'?'<button onclick="showPage(\'customers\')">＋ کاربر پنل</button>':''}</div></div><div class="card"><h3>وضعیت</h3><p class="muted">احراز هویت از Backend انجام می‌شود و رمزها به‌صورت Hash در دیتابیس ذخیره می‌شوند.</p></div></div></section>`}
async function customers(){const a=await api('/api/customers');return `<section class="page"><div class="head"><div><h2>کاربران پنل</h2><p>برای هر شخص یک حساب محدود بسازید تا پنل خودش را داشته باشد.</p></div><button class="primary" onclick="openCustomer()">＋ ایجاد کاربر پنل</button></div><div class="card">${table(['نام','Username','وضعیت','عملیات'],a.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.username)}</td><td><span class="badge ${c.status==='active'?'active':'inactive'}">${c.status==='active'?'فعال':'غیرفعال'}</span></td><td><button class="action" onclick="openCustomer(${c.id})">ویرایش</button><button class="action danger" onclick="delApi('/api/customers/${c.id}','کاربر پنل حذف شود؟','customers')">حذف</button></td></tr>`).join(''))}</div></section>`}
async function admins(){const a=await api('/api/admins');return `<section class="page"><div class="head"><div><h2>مدیران</h2><p>مدیران فقط با حساب واقعی Backend وارد می‌شوند.</p></div><button class="primary" onclick="openAdmin()">＋ ایجاد مدیر</button></div><div class="card">${table(['Username','عملیات'],a.map(x=>`<tr><td>${esc(x.username)}</td><td><button class="action" onclick="openAdmin(${x.id})">ویرایش</button><button class="action danger" onclick="delApi('/api/admins/${x.id}','این مدیر حذف شود؟','admins')">حذف</button></td></tr>`).join(''))}</div></section>`}
async function servers(){const a=await api('/api/servers');return `<section class="page"><div class="head"><div><h2>سرورها</h2><p>مدیریت سرورهای متصل.</p></div><button class="primary" onclick="openServer()">＋ افزودن سرور</button></div><div class="server-grid">${a.map(s=>`<div class="server"><h3>${esc(s.name)}</h3><p>${esc(s.url)}</p><p><span class="dot ${s.status!=='online'?'off':''}"></span>${esc(s.status||'online')}</p><button class="action" onclick="openServer(${s.id})">ویرایش</button><button class="action danger" onclick="delApi('/api/servers/${s.id}','سرور حذف شود؟','servers')">حذف</button></div>`).join('')||'<div class="card empty">سروری ثبت نشده است.</div>'}</div></section>`}
async function users(){const a=await api('/api/users');return `<section class="page"><div class="head"><div><h2>کاربران</h2><p>${state.session.role==='admin'?'مدیریت همه کاربران':'مدیریت کاربران اختصاصی شما'}</p></div><button class="primary" onclick="openUser()">＋ ساخت کاربر</button></div><div class="card">${table(['نام','پلن','حجم','انقضا','عملیات'],a.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.plan)}</td><td>${esc(u.gb)} GB</td><td>${esc(u.date)}</td><td><button class="action" onclick="openUser(${u.id})">ویرایش</button><button class="action danger" onclick="delApi('/api/users/${u.id}','کاربر حذف شود؟','users')">حذف</button></td></tr>`).join(''))}</div></section>`}
async function services(){const a=await api('/api/services');return `<section class="page"><div class="head"><div><h2>سرویس‌ها</h2><p>ایجاد، ویرایش و حذف سرویس‌ها.</p></div><button class="primary" onclick="openService()">＋ ساخت سرویس</button></div><div class="card">${table(['نام','کاربر','سرور','لینک','عملیات'],a.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.user)}</td><td>${esc(s.server)}</td><td><button class="action" onclick="copyText('${esc(s.link)}')">کپی</button></td><td><button class="action" onclick="openService(${s.id})">ویرایش</button><button class="action danger" onclick="delApi('/api/services/${s.id}','سرویس حذف شود؟','services')">حذف</button></td></tr>`).join(''))}</div></section>`}
async function plans(){const a=await api('/api/plans');return `<section class="page"><div class="head"><div><h2>پلن‌ها</h2><p>پلن‌های قابل استفاده در پنل.</p></div><button class="primary" onclick="openPlan()">＋ ساخت پلن</button></div><div class="card">${table(['نام','حجم','مدت','عملیات'],a.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.gb)} GB</td><td>${esc(p.days)} روز</td><td><button class="action" onclick="openPlan(${p.id})">ویرایش</button><button class="action danger" onclick="delApi('/api/plans/${p.id}','پلن حذف شود؟','plans')">حذف</button></td></tr>`).join(''))}</div></section>`}
async function logs(){const a=await api('/api/logs');return `<section class="page"><div class="head"><div><h2>گزارش‌ها</h2><p>رویدادهای ثبت‌شده.</p></div><button class="primary" onclick="delApi('/api/logs','همه گزارش‌های قابل مشاهده حذف شوند؟','logs')">پاک کردن گزارش‌ها</button></div><div class="card">${a.map(x=>`<p class="log">● ${esc(x.text)} <small>${esc(x.time)}</small></p>`).join('')||'<div class="empty">گزارشی وجود ندارد.</div>'}</div></section>`}
function account(){const u=state.session.role==='admin'?state.session.admin.username:state.session.customer.username;return `<section class="page"><div class="head"><div><h2>حساب کاربری</h2><p>با ذخیره تغییرات، Session قبلی فوراً باطل می‌شود و باید دوباره وارد شوید.</p></div></div><div class="card settings"><label>Username جدید<input id="accountUsername" value="${esc(u)}" minlength="3"></label><label>Password جدید<input id="accountPassword" type="password" minlength="8" placeholder="حداقل ۸ کاراکتر"></label><label>تکرار Password جدید<input id="accountPassword2" type="password" minlength="8"></label><button class="primary" onclick="changeMyAccount()">ذخیره و خروج</button></div></section>`}
async function changeMyAccount(){const username=$('#accountUsername').value.trim(),p=$('#accountPassword').value,p2=$('#accountPassword2').value;if(username.length<3)return alert('Username باید حداقل ۳ کاراکتر باشد.');if(p&&p.length<8)return alert('Password جدید باید حداقل ۸ کاراکتر باشد.');if(p!==p2)return alert('تکرار Password یکسان نیست.');try{await api('/api/account/me',{method:'PUT',body:JSON.stringify({username,password:p||undefined,passwordConfirm:p2||undefined})});alert('اطلاعات تغییر کرد. لطفاً دوباره Login کنید.');logout()}catch(e){alert(e.message)}}
function modal(t,b,fn){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modalSave').onclick=async()=>{try{await fn();closeModal()}catch(e){alert(e.message)}};$('#modal').classList.add('show')}function closeModal(){$('#modal').classList.remove('show')}function field(id,label,v='',type='text'){return `<label>${label}<input id="${id}" type="${type}" value="${esc(v)}"></label>`}
async function openCustomer(id){let a=id?(await api('/api/customers')).find(x=>x.id===id):{};modal(id?'ویرایش کاربر پنل':'ایجاد کاربر پنل',field('f1','نام',a?.name||'')+field('f2','Username',a?.username||'')+field('f3',id?'رمز جدید (اختیاری)':'رمز عبور','', 'password')+`<label>وضعیت<select id="f4"><option value="active" ${a?.status==='active'||!id?'selected':''}>فعال</option><option value="inactive" ${a?.status==='inactive'?'selected':''}>غیرفعال</option></select></label>`,async()=>{const b={name:$('#f1').value.trim(),username:$('#f2').value.trim(),status:$('#f4').value};if($('#f3').value)b.password=$('#f3').value;await api(id?'/api/customers/'+id:'/api/customers',{method:id?'PUT':'POST',body:JSON.stringify(b)});await showPage('customers')})}
async function openAdmin(id){let a=id?(await api('/api/admins')).find(x=>x.id===id):{};modal(id?'ویرایش مدیر':'ایجاد مدیر',field('f1','Username',a?.username||'')+field('f2',id?'رمز جدید':'رمز عبور','','password'),async()=>{const b={username:$('#f1').value.trim()};if($('#f2').value)b.password=$('#f2').value;await api(id?'/api/admins/'+id:'/api/admins',{method:id?'PUT':'POST',body:JSON.stringify(b)});if(id&&id===state.session.admin.id){alert('اطلاعات این مدیر تغییر کرد؛ Session باطل شد.');logout();return}await showPage('admins')})}
async function openServer(id){let a=id?(await api('/api/servers')).find(x=>x.id===id):{};modal(id?'ویرایش سرور':'افزودن سرور',field('f1','نام',a?.name||'')+field('f2','آدرس',a?.url||'')+field('f3','Token',a?.token||'','password')+`<label>وضعیت<select id="f4"><option>online</option><option>offline</option></select></label>`,async()=>{await api(id?'/api/servers/'+id:'/api/servers',{method:id?'PUT':'POST',body:JSON.stringify({name:$('#f1').value.trim(),url:$('#f2').value.trim(),token:$('#f3').value,status:$('#f4').value})});await showPage('servers')});setTimeout(()=>{if(a?.status)$('#f4').value=a.status},0)}
async function openUser(id){let a=id?(await api('/api/users')).find(x=>x.id===id):{};modal(id?'ویرایش کاربر':'ساخت کاربر',field('f1','نام',a?.name||'')+field('f2','پلن',a?.plan||'')+field('f3','حجم GB',a?.gb||100)+field('f4','تاریخ انقضا',a?.date||''),async()=>{await api(id?'/api/users/'+id:'/api/users',{method:id?'PUT':'POST',body:JSON.stringify({name:$('#f1').value.trim(),plan:$('#f2').value.trim(),gb:$('#f3').value,date:$('#f4').value})});await showPage('users')})}
async function openService(id){let a=id?(await api('/api/services')).find(x=>x.id===id):{};modal(id?'ویرایش سرویس':'ساخت سرویس',field('f1','نام سرویس',a?.name||'')+field('f2','کاربر',a?.user||'')+field('f3','سرور',a?.server||'')+field('f4','لینک اتصال',a?.link||''),async()=>{await api(id?'/api/services/'+id:'/api/services',{method:id?'PUT':'POST',body:JSON.stringify({name:$('#f1').value.trim(),user:$('#f2').value.trim(),server:$('#f3').value.trim(),link:$('#f4').value.trim()})});await showPage('services')})}
async function openPlan(id){let a=id?(await api('/api/plans')).find(x=>x.id===id):{};modal(id?'ویرایش پلن':'ساخت پلن',field('f1','نام پلن',a?.name||'')+field('f2','حجم GB',a?.gb||100)+field('f3','مدت روز',a?.days||30),async()=>{await api(id?'/api/plans/'+id:'/api/plans',{method:id?'PUT':'POST',body:JSON.stringify({name:$('#f1').value.trim(),gb:$('#f2').value,days:$('#f3').value})});await showPage('plans')})}
async function delApi(path,msg,page){if(!confirm(msg))return;try{await api(path,{method:'DELETE'});await showPage(page)}catch(e){alert(e.message)}}
function copyText(x){navigator.clipboard?.writeText(x);alert('کپی شد')}
$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#theme').onclick=()=>document.body.classList.toggle('dark');window.addEventListener('DOMContentLoaded',restore);
