const KEY='strix_vip_v1_1';let db=JSON.parse(localStorage.getItem(KEY)||'null')||{customers:[{id:'c1',name:'مشتری نمونه',user:'customer',pass:'customer',status:'active'}],servers:[],users:[],services:[],plans:[],logs:[],settings:{name:'STRIX VIP PANEL',desc:'پنل مدیریت اصلی'}};let session=null;
const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(db));render()}async function checkSetup(){try{let r=await fetch('/api/setup/status');let x=await r.json();if(x.needsSetup){$('#login')?.classList.add('hidden');$('#setup')?.classList.remove('hidden')}}catch(e){}}
async function createFirstAdmin(){let username=$('#setupUser').value.trim(),password=$('#setupPass').value;if(!username||password.length<8)return alert('نام کاربری و رمز حداقل ۸ کاراکتر لازم است');let r=await fetch('/api/setup/create-admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});let x=await r.json();if(!r.ok)return alert(x.error||'خطا');alert('ادمین ساخته شد؛ حالا وارد شوید');$('#setup').classList.add('hidden');$('#login').classList.remove('hidden')}
async function login(){let r=$('#loginRole').value,u=$('#loginUser').value,p=$('#loginPass').value;let res=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})}).then(x=>x.json()).catch(()=>null);if(!res?.token)return alert('نام کاربری یا رمز عبور اشتباه است');if(r==='admin'&&res.role!=='admin')return alert('این حساب مدیر نیست');if(r==='customer'&&res.role!=='customer')return alert('این حساب مشتری نیست');session={role:res.role,customer:res.customer?.id||null,token:res.token};$('#login').classList.add('hidden');$('#app').classList.remove('hidden');buildNav();showPage('dashboard');loadAdmins()}function logout(){session=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden')}
function buildNav(){let admin=session.role==='admin';let items=admin?[['dashboard','⌂','داشبورد'],['customers','♟','مشتریان پنل'],['admins','🛡','مدیران'],['servers','◈','سرورها'],['users','♙','کاربران'],['services','🔗','سرویس‌ها'],['plans','▣','پلن‌ها'],['logs','≡','گزارش‌ها'],['settings','⚙','تنظیمات']]:[['dashboard','⌂','داشبورد'],['users','♙','کاربران'],['services','🔗','سرویس‌ها'],['plans','▣','پلن‌ها'],['settings','⚙','تنظیمات']];$('#nav').innerHTML=items.map(x=>`<button class="nav" data-page="${x[0]}" onclick="showPage('${x[0]}')">${x[1]} <span>${x[2]}</span></button>`).join('');$('#roleText').textContent=admin?'مدیر اصلی':'مشتری پنل';$('#who').textContent=admin?'مدیر اصلی':db.customers.find(x=>x.id===session.customer)?.name||'مشتری';$('#whoSub').textContent=admin?'Administrator':'Customer';$('#avatar').textContent=admin?'A':'C'}
function owned(arr){if(session.role==='admin')return arr;let cid=session.customer;return arr.filter(x=>x.customerId===cid)}function addOwned(x){if(session.role==='customer')x.customerId=session.customer;return x}
function showPage(id){let titles={dashboard:['داشبورد','نمای کلی'],customers:['مشتریان پنل','ساخت پنل برای هر مشتری'],admins:['مدیران','مدیریت حساب‌های مدیر'],servers:['سرورها','مدیریت سرورهای Marzban'],users:['کاربران','مدیریت کاربران'],services:['سرویس‌ها','لینک‌های اتصال'],plans:['پلن‌ها','پلن‌های قابل تعریف'],logs:['گزارش‌ها','رویدادها'],settings:['تنظیمات','تنظیمات']};$('#title').textContent=titles[id][0];$('#sub').textContent=titles[id][1];document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));let c=$('#content');if(id==='dashboard')c.innerHTML=dashboard();if(id==='customers')c.innerHTML=customers();if(id==='admins')c.innerHTML=admins();if(id==='servers')c.innerHTML=servers();if(id==='users')c.innerHTML=users();if(id==='services')c.innerHTML=services();if(id==='plans')c.innerHTML=plans();if(id==='logs')c.innerHTML=logs();if(id==='settings')c.innerHTML=settings();if(innerWidth<821)$('#sidebar').classList.remove('open')}
function dashboard(){let u=owned(db.users),s=session.role==='admin'?db.servers:[],sv=owned(db.services);return `<section class=page><div class=head><div><h2>سلام 👋</h2><p>${session.role==='admin'?'مدیریت کل سیستم':'پنل اختصاصی شما'}</p></div></div><div class=stats><div class=stat><b>کاربران</b><strong>${u.length}</strong></div><div class=stat><b>سرویس‌ها</b><strong>${sv.length}</strong></div><div class=stat><b>${session.role==='admin'?'سرورها':'پلن‌ها'}</b><strong>${session.role==='admin'?s.length:owned(db.plans).length}</strong></div><div class=stat><b>وضعیت حساب</b><strong>فعال</strong></div></div><div class=card><h3>${session.role==='admin'?'ساختار چندمشتری':'پنل اختصاصی مشتری'}</h3><p>${session.role==='admin'?'هر مشتری اطلاعات جداگانه، کاربران و سرویس‌های خودش را دارد. مدیر اصلی دسترسی کامل دارد.':'اطلاعات این حساب از سایر مشتریان جداست و فقط موارد اختصاص داده‌شده به شما نمایش داده می‌شود.'}</p></div></section>`}
function table(rows,heads){return `<div class=table><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan=${heads.length}><div class=empty>موردی وجود ندارد</div></td></tr>`}</tbody></table></div>`}
function customers(){let rows=db.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.user)}</td><td><span class="badge ${c.status==='active'?'active':'inactive'}">${c.status==='active'?'فعال':'غیرفعال'}</span></td><td><button class=action onclick="openCustomer('${c.id}')">ویرایش</button> <button class="action danger" onclick="delCustomer('${c.id}')">حذف</button></td></tr>`).join('');return `<section class=page><div class=head><div><h2>مشتریان پنل</h2><p>هر مشتری یک محیط مستقل دارد.</p></div><button class=primary onclick=openCustomer()>＋ ساخت مشتری</button></div><div class=card>${table(rows,['نام','نام کاربری','وضعیت','عملیات'])}</div></section>`}
function admins(){if(session.role!=='admin')return `<section class=page><div class=card>دسترسی غیرمجاز</div></section>`;return `<section class=page><div class=head><div><h2>مدیران</h2><p>حساب‌های ورود مدیر قابل مدیریت هستند.</p></div><button class=primary onclick=openAdmin>＋ ساخت ادمین</button></div><div class=card>${table(window._admins?.map(a=>`<tr><td>${esc(a.username)}</td><td><button class=action onclick="openAdmin(${a.id})">ویرایش</button> <button class="action danger" onclick="delAdmin(${a.id})">حذف</button></td></tr>`).join('')||'', ['نام کاربری','عملیات'])}</div></section>`}
async function loadAdmins(){if(session?.role!=='admin')return;let r=await fetch('/api/admins',{headers:{Authorization:'Bearer '+session.token}});if(r.ok){window._admins=await r.json();if(document.querySelector('.nav.active')?.dataset.page==='admins')showPage('admins')}}
function openAdmin(id){let a=(window._admins||[]).find(x=>x.id===id)||{};openModal(id?'ویرایش ادمین':'ساخت ادمین',inp('f1','نام کاربری',a.username)+inp('f2','رمز عبور',''),async()=>{let body={username:$('#f1').value};if($('#f2').value)body.password=$('#f2').value;let url=id?'/api/admins/'+id:'/api/admins',method=id?'PUT':'POST';let r=await fetch(url,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+session.token},body:JSON.stringify(body)});if(!r.ok){let e=await r.json();return alert(e.error||'خطا')}closeModal();loadAdmins()})}
async function delAdmin(id){if(!confirm('این ادمین حذف شود؟'))return;let r=await fetch('/api/admins/'+id,{method:'DELETE',headers:{Authorization:'Bearer '+session.token}});if(!r.ok){let e=await r.json();return alert(e.error||'خطا')}loadAdmins()}
function servers(){if(session.role!=='admin')return `<section class=page><div class=card>دسترسی به مدیریت سرورها فقط برای مدیر اصلی است.</div></section>`;return `<section class=page><div class=head><div><h2>سرورها</h2><p>سرورهای Marzban را اینجا مدیریت کن.</p></div><button class=primary onclick=openServer()>＋ افزودن سرور</button></div><div class=server-grid>${db.servers.map(s=>`<div class=server><h3><i class="dot ${s.status==='off'?'off':''}"></i>${esc(s.name)}</h3><p>${esc(s.url)}</p><button class=action onclick="openServer('${s.id}')">ویرایش</button> <button class="action danger" onclick="delServer('${s.id}')">حذف</button></div>`).join('')||'<div class="card empty">سروری ثبت نشده</div>'}</div></section>`}
function users(){let a=owned(db.users);return `<section class=page><div class=head><div><h2>کاربران</h2><p>کاربران فقط متعلق به همین پنل نمایش داده می‌شوند.</p></div><button class=primary onclick=openUser>＋ ساخت کاربر</button></div><div class=card>${table(a.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.plan)}</td><td>${esc(u.gb)} GB</td><td>${esc(u.date)}</td><td><button class=action onclick="openUser('${u.id}')">ویرایش</button> <button class="action danger" onclick="delUser('${u.id}')">حذف</button></td></tr>`).join(''),['نام','پلن','حجم','انقضا','عملیات'])}</div></section>`}
function services(){let a=owned(db.services);return `<section class=page><div class=head><div><h2>سرویس‌ها</h2><p>لینک‌های هر مشتری جداست.</p></div><button class=primary onclick=openService>＋ ساخت سرویس</button></div><div class=card>${table(a.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.user)}</td><td>${esc(s.server)}</td><td><button class=action onclick="navigator.clipboard?.writeText('${esc(s.link)}');alert('کپی شد')">کپی لینک</button></td><td><button class=action onclick="openService('${s.id}')">ویرایش</button> <button class="action danger" onclick="delService('${s.id}')">حذف</button></td></tr>`).join(''),['نام','کاربر','سرور','لینک','عملیات'])}</div></section>`}
function plans(){let a=owned(db.plans);return `<section class=page><div class=head><div><h2>پلن‌ها</h2><p>در شروع کاملاً خالی است.</p></div><button class=primary onclick=openPlan>＋ ساخت پلن</button></div><div class=card>${table(a.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.gb)} GB</td><td>${esc(p.days)} روز</td><td><button class=action onclick="openPlan('${p.id}')">ویرایش</button> <button class="action danger" onclick="delPlan('${p.id}')">حذف</button></td></tr>`).join(''),['نام','حجم','مدت','عملیات'])}</div></section>`}
function logs(){let a=session.role==='admin'?db.logs:db.logs.filter(x=>x.customerId===session.customer);return `<section class=page><div class=head><h2>گزارش‌ها</h2><button class="dangerBtn" onclick="db.logs=db.logs.filter(x=>${session.role==='admin'}?false:x.customerId!==session.customer);save()">پاک کردن</button></div><div class=card>${a.map(x=>`<p>● ${esc(x.text)} <small>${esc(x.time)}</small></p>`).join('')||'<div class=empty>گزارشی وجود ندارد</div>'}</div></section>`}
function settings(){return `<section class=page><div class=head><h2>تنظیمات</h2></div><div class="card settings"><label>نام نمایشی<input id=set1 value="${esc(db.settings.name)}"></label><label>توضیحات<input id=set2 value="${esc(db.settings.desc)}"></label><button class=primary onclick="db.settings.name=$('#set1').value;db.settings.desc=$('#set2').value;save();alert('ذخیره شد')">ذخیره</button></div></section>`}
function openModal(t,b,fn){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modalSave').onclick=fn;$('#modal').classList.add('show')}function closeModal(){$('#modal').classList.remove('show')}function inp(id,l,v=''){return `<label>${l}<input id=${id} value="${esc(v)}"></label>`}
function openCustomer(id){let c=db.customers.find(x=>x.id===id)||{};openModal(id?'ویرایش مشتری':'ساخت مشتری',inp('f1','نام',c.name)+inp('f2','نام کاربری',c.user)+inp('f3','رمز عبور',c.pass)+`<label>وضعیت<select id=f4><option value=active>فعال</option><option value=inactive>غیرفعال</option></select></label>`,()=>{let x={id:id||crypto.randomUUID(),name:$('#f1').value,user:$('#f2').value,pass:$('#f3').value,status:$('#f4').value};if(id)Object.assign(c,x);else db.customers.push(x);closeModal();save()});if(id)$('#f4').value=c.status}
function delCustomer(id){if(confirm('مشتری حذف شود؟')){db.customers=db.customers.filter(x=>x.id!==id);db.users=db.users.filter(x=>x.customerId!==id);db.services=db.services.filter(x=>x.customerId!==id);db.plans=db.plans.filter(x=>x.customerId!==id);save()}}
function openServer(id){let s=db.servers.find(x=>x.id===id)||{};openModal(id?'ویرایش سرور':'افزودن سرور',inp('f1','نام',s.name)+inp('f2','آدرس',s.url),()=>{let x={id:id||crypto.randomUUID(),name:$('#f1').value,url:$('#f2').value,status:'online'};if(id)Object.assign(s,x);else db.servers.push(x);closeModal();save()})}function delServer(id){if(confirm('حذف؟')){db.servers=db.servers.filter(x=>x.id!==id);save()}}
function openUser(id){let u=db.users.find(x=>x.id===id)||{};openModal(id?'ویرایش کاربر':'ساخت کاربر',inp('f1','نام کاربری',u.name)+inp('f2','پلن',u.plan)+inp('f3','حجم GB',u.gb||100)+inp('f4','تاریخ انقضا',u.date),()=>{let x=addOwned({id:id||crypto.randomUUID(),name:$('#f1').value,plan:$('#f2').value,gb:$('#f3').value,date:$('#f4').value});if(id)Object.assign(u,x);else db.users.push(x);closeModal();save()})}function delUser(id){if(confirm('حذف؟')){db.users=db.users.filter(x=>x.id!==id);save()}}
function openService(id){let s=db.services.find(x=>x.id===id)||{};openModal(id?'ویرایش سرویس':'ساخت سرویس',inp('f1','نام سرویس',s.name)+inp('f2','کاربر',s.user)+inp('f3','سرور',s.server)+inp('f4','لینک',s.link||'vless://...'),()=>{let x=addOwned({id:id||crypto.randomUUID(),name:$('#f1').value,user:$('#f2').value,server:$('#f3').value,link:$('#f4').value});if(id)Object.assign(s,x);else db.services.push(x);closeModal();save()})}function delService(id){if(confirm('حذف؟')){db.services=db.services.filter(x=>x.id!==id);save()}}
function openPlan(id){let p=db.plans.find(x=>x.id===id)||{};openModal(id?'ویرایش پلن':'ساخت پلن',inp('f1','نام پلن',p.name)+inp('f2','حجم GB',p.gb||100)+inp('f3','مدت روز',p.days||30),()=>{let x=addOwned({id:id||crypto.randomUUID(),name:$('#f1').value,gb:$('#f2').value,days:$('#f3').value});if(id)Object.assign(p,x);else db.plans.push(x);closeModal();save()})}function delPlan(id){if(confirm('حذف؟')){db.plans=db.plans.filter(x=>x.id!==id);save()}}
function render(){if(session)showPage(document.querySelector('.nav.active')?.dataset.page||'dashboard')}
$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');$('#theme').onclick=()=>document.body.classList.toggle('dark');
window.addEventListener("DOMContentLoaded",checkSetup);
